spring.datasource.url=${jdbc:postgresql://pg-1892f17d-saitejagangireddi-f394.i.aivencloud.com:25012/defaultdb?sslmode=require}
spring.datasource.username=${avnadmin}
spring.datasource.password=${AVNS_eb6PskTeoLJ0t2n7uTf}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true